"""
RenderService: Generate localized Markdown resumes, social card data, and PDF exports.
"""

from textwrap import wrap
from typing import List

from models import AIInsights, CardData, GitScore, UserData
from services.skills_inference import SkillsInferenceService


class RenderService:
    """Service for generating resumes and social cards from GitHub data."""

    COPY = {
        "en": {
            "score_breakdown": "Score Breakdown",
            "project_impact": "Project Reach",
            "code_contribution": "Contribution Output",
            "community_activity": "Community Activity",
            "tech_breadth": "Stack Range",
            "documentation": "Documentation",
            "key_strengths": "Key Strengths",
            "technical_skills": "Technical Skills",
            "specializations": "Specializations",
            "expert": "Expert",
            "proficient": "Proficient",
            "familiar": "Familiar",
            "learning": "Learning",
            "tech_stack": "Tech Stack",
            "language_distribution": "Language Distribution",
            "language_unavailable": "Language distribution was not available.",
            "top_projects": "Top Projects",
            "no_projects": "No public repositories were available for ranking.",
            "stars": "stars",
            "forks": "forks",
            "language": "Language",
            "ai_insights": "AI Insights",
            "style_tags": "Style Tags",
            "summary": "Summary",
            "roast": "Roast",
            "ai_unavailable": "AI insights were unavailable for this run.",
            "contribution_stats": "Contribution Stats",
            "total_commits": "Total Commits (Last Year)",
            "total_pull_requests": "Total Pull Requests",
            "followers": "Followers",
            "following": "Following",
            "longest_streak": "Longest Streak",
            "days": "days",
            "generalist": "Generalist",
            "card_fallback": "GitHub profile snapshot generated by Codefolio.",
            "card_roast_fallback": "Polished enough for a recruiter, nerdy enough for a maintainer.",
            "card_metrics": ["Reach", "Output", "Community", "Range", "Docs"],
            "lang": "en",
            "profile_overview": "Profile Overview",
            "dev_type": "Developer Type",
            "activity_level": "Activity Level",
            "repo_stats": "Repository Stats",
            "total_repos": "Total Repositories",
            "total_stars": "Total Stars",
            "total_forks": "Total Forks",
            "avg_stars": "Average Stars per Repo",
            "top_languages": "Top Languages",
            "contribution_graph": "Contribution Activity",
            "achievements": "Achievements",
            "high_impact": "High Impact",
            "active_contributor": "Active Contributor",
            "diverse_skills": "Diverse Skills",
            "well_documented": "Well Documented",
            "popular_repo": "Popular Repository",
            "consistent": "Consistent Committer",
            "resume_tagline": "",
            "about_label": "About",
            "professional_summary": "Professional summary",
            "contact_heading": "Contact",
            "summary_heading": "Professional highlights",
            "github_contact_label": "GitHub",
            "bio_bullet_label": "GitHub bio",
            "public_activity_heading": "Public activity",
            "score_reference_heading": "Profile metrics (reference)",
            "keywords_heading": "Keywords",
            "github_impact_heading": "GitHub footprint & GitScore",
            "composite_gitscore_label": "Composite GitScore",
            "activity_reach": "Activity & reach",
            "profile_style_heading": "Style signals (AI)",
            "data_attribution": "Generated by Codefolio from public GitHub data only.",
            "repo_url_label": "Link",
            "notable_projects": "Selected projects",
        },
        "zh": {
            "score_breakdown": "评分拆解",
            "project_impact": "项目影响力",
            "code_contribution": "代码贡献",
            "community_activity": "社区活跃度",
            "tech_breadth": "技术广度",
            "documentation": "文档完善度",
            "key_strengths": "核心优势",
            "technical_skills": "技术技能",
            "specializations": "专业方向",
            "expert": "精通",
            "proficient": "熟练",
            "familiar": "了解",
            "learning": "学习中",
            "tech_stack": "技术栈",
            "language_distribution": "语言分布",
            "language_unavailable": "暂无可用的语言分布数据。",
            "top_projects": "代表项目",
            "no_projects": "没有可用于展示排序的公开仓库。",
            "stars": "星标",
            "forks": "Fork",
            "language": "语言",
            "ai_insights": "AI 洞察",
            "style_tags": "风格标签",
            "summary": "总结",
            "roast": "吐槽",
            "ai_unavailable": "这次生成未获得 AI 洞察。",
            "contribution_stats": "贡献数据",
            "total_commits": "近一年提交数",
            "total_pull_requests": "Pull Request 数",
            "followers": "关注者",
            "following": "正在关注",
            "longest_streak": "最长连续活跃",
            "days": "天",
            "generalist": "多面手",
            "card_fallback": "Codefolio 生成的 GitHub 档案快照。",
            "card_roast_fallback": "既能给招聘方看，也保留了工程师味道。",
            "card_metrics": ["影响", "代码", "社区", "广度", "文档"],
            "lang": "zh-CN",
            "profile_overview": "档案概览",
            "dev_type": "开发者类型",
            "activity_level": "活跃程度",
            "repo_stats": "仓库统计",
            "total_repos": "仓库总数",
            "total_stars": "总星标数",
            "total_forks": "总 Fork 数",
            "avg_stars": "平均星标",
            "top_languages": "主要语言",
            "contribution_graph": "贡献活动",
            "achievements": "成就徽章",
            "high_impact": "高影响力",
            "active_contributor": "活跃贡献者",
            "diverse_skills": "技能多样",
            "well_documented": "文档完善",
            "popular_repo": "热门仓库",
            "consistent": "持续提交",
            "resume_tagline": "",
            "about_label": "简介",
            "professional_summary": "职业概述",
            "contact_heading": "联系信息",
            "summary_heading": "专业摘要",
            "github_contact_label": "GitHub",
            "bio_bullet_label": "简介",
            "public_activity_heading": "公开活动",
            "score_reference_heading": "档案指标（参考）",
            "keywords_heading": "关键词",
            "github_impact_heading": "GitHub 足迹与 GitScore",
            "composite_gitscore_label": "综合 GitScore",
            "activity_reach": "活跃度与影响力",
            "profile_style_heading": "风格特征（AI）",
            "data_attribution": "本文由 Codefolio 根据 GitHub 公开数据自动生成。",
            "repo_url_label": "链接",
            "notable_projects": "项目经历",
        },
    }

    @staticmethod
    def _normalize_summary_bullets(text: str) -> List[str]:
        """Turn AI or fallback summary into markdown bullet lines."""
        raw = (text or "").strip()
        if not raw:
            return []
        parts = [ln.strip() for ln in raw.splitlines() if ln.strip()]
        out: List[str] = []
        for s in parts:
            if s.startswith("- "):
                out.append(s)
            elif s.startswith("•"):
                out.append("- " + s[1:].strip())
            else:
                out.append("- " + s)
        if out:
            return out
        return ["- " + raw]

    def generate_markdown_resume(
        self,
        user_data: UserData,
        gitscore: GitScore,
        ai_insights: AIInsights,
        language: str = "en",
    ) -> str:
        """Generate CV-style Markdown: contact, bullet highlights, skills, projects, activity, metrics."""
        copy = self.COPY[language]
        lines: List[str] = []

        total_stars = sum(repo.stars for repo in user_data.repositories)
        total_forks = sum(repo.forks for repo in user_data.repositories)
        repo_count = len(user_data.repositories)
        profile_url = f"https://github.com/{user_data.username}"

        display_name = (user_data.name or "").strip() or user_data.username

        lines.append(f"# {display_name}")
        lines.append("")
        lines.append(f"## {copy['contact_heading']}")
        lines.append("")
        lines.append(
            f"- **{copy['github_contact_label']}:** [{user_data.username}]({profile_url})"
        )
        if user_data.bio:
            lines.append(f"- **{copy['bio_bullet_label']}:** {user_data.bio}")
        lines.append("")

        tech_summary = (ai_insights.tech_summary or "").strip()
        summary_lines = self._normalize_summary_bullets(tech_summary)
        if summary_lines:
            lines.append(f"## {copy['summary_heading']}")
            lines.append("")
            lines.extend(summary_lines)
            lines.append("")

        lines.append(f"## {copy['technical_skills']}")
        lines.append("")

        if user_data.languages:
            total_bytes = sum(user_data.languages.values())
            top_langs = sorted(user_data.languages.items(), key=lambda x: x[1], reverse=True)[:5]
            lines.append(f"**{copy['language_distribution']}**")
            lines.append("")
            for lang_name, byte_count in top_langs:
                pct = (byte_count / total_bytes * 100) if total_bytes > 0 else 0.0
                lines.append(f"- **{lang_name}:** {pct:.1f}%")
            lines.append("")

        skills_service = SkillsInferenceService()
        skills_by_level = skills_service.infer_skills(user_data)
        specializations = skills_service.infer_specializations(user_data)

        if specializations:
            lines.append(f"**{copy['specializations']}:** {', '.join(specializations)}")
            lines.append("")

        for level in ["Expert", "Proficient", "Familiar", "Learning"]:
            bucket = skills_by_level.get(level, [])
            if bucket:
                level_label = copy.get(level.lower(), level)
                lines.append(f"- **{level_label}:** {', '.join(bucket)}")
        lines.append("")

        lines.append(f"## {copy['notable_projects']}")
        lines.append("")
        top_repos = sorted(
            user_data.repositories,
            key=lambda repo: (repo.stars, repo.forks),
            reverse=True,
        )[:5]

        if not top_repos:
            lines.append(copy["no_projects"])
            lines.append("")
        else:
            for repo in top_repos:
                lines.append(f"### {repo.name}")
                lines.append("")
                meta_bits: List[str] = []
                if repo.language:
                    meta_bits.append(repo.language)
                if repo.stars > 0:
                    meta_bits.append(f"⭐ {repo.stars}")
                if repo.forks > 0:
                    meta_bits.append(f"🔀 {repo.forks}")
                if meta_bits:
                    lines.append(f"*{' · '.join(meta_bits)}*")
                    lines.append("")
                if repo.description:
                    lines.append(f"- {repo.description}")
                lines.append(f"- **{copy['repo_url_label']}:** {repo.url}")
                lines.append("")

        lines.append(f"## {copy['public_activity_heading']}")
        lines.append("")
        lines.append(f"- **{copy['total_repos']}:** {repo_count}")
        lines.append(f"- **{copy['total_stars']}:** {total_stars}")
        lines.append(f"- **{copy['total_forks']}:** {total_forks}")
        lines.append(f"- **{copy['total_commits']}:** {user_data.contributions.total_commits_last_year}")
        lines.append(f"- **{copy['total_pull_requests']}:** {user_data.contributions.total_prs_last_year}")
        lines.append(f"- **{copy['followers']}:** {user_data.followers}")
        lines.append(f"- **{copy['following']}:** {user_data.following}")
        if user_data.contributions.longest_streak > 0:
            lines.append(
                f"- **{copy['longest_streak']}:** {user_data.contributions.longest_streak} {copy['days']}"
            )
        lines.append("")

        lines.append(f"## {copy['score_reference_heading']}")
        lines.append("")
        lines.append(f"- **{copy['composite_gitscore_label']}:** **{gitscore.total:.1f}** / 100")
        lines.append("")
        lines.append(f"### {copy['score_breakdown']}")
        lines.append("")
        dimension_rows = [
            ("impact", copy["project_impact"], 35),
            ("contribution", copy["code_contribution"], 25),
            ("community", copy["community_activity"], 20),
            ("tech_breadth", copy["tech_breadth"], 15),
            ("documentation", copy["documentation"], 5),
        ]
        for dim_key, label, cap in dimension_rows:
            score = gitscore.dimensions.get(dim_key, 0.0)
            lines.append(f"- **{label}:** {score:.1f} / {cap}")
        lines.append("")

        if ai_insights.style_tags:
            lines.append(f"## {copy['keywords_heading']}")
            lines.append("")
            lines.append(" · ".join(ai_insights.style_tags))
            lines.append("")

        lines.append(f"*{copy['data_attribution']}*")
        lines.append("")

        return "\n".join(lines)

    def _build_profile_overview(self, user_data: UserData, gitscore: GitScore, copy: dict) -> str:
        """Build profile overview section with key stats."""
        lines = []
        
        # Calculate total stars and forks
        total_stars = sum(repo.stars for repo in user_data.repositories)
        total_forks = sum(repo.forks for repo in user_data.repositories)
        repo_count = len(user_data.repositories)
        avg_stars = total_stars / repo_count if repo_count > 0 else 0
        
        # Developer type based on gitscore dimensions
        dimensions = gitscore.dimensions
        max_dim = max(dimensions.items(), key=lambda x: x[1])
        dev_types = {
            "impact": "Open Source Influencer",
            "contribution": "Core Contributor", 
            "community": "Community Builder",
            "tech_breadth": "Full Stack Developer",
            "documentation": "Technical Writer",
        }
        dev_type = dev_types.get(max_dim[0], "Developer")
        
        # Activity level
        commits = user_data.contributions.total_commits_last_year
        if commits > 1000:
            activity = "🔥 Very High"
        elif commits > 500:
            activity = "⚡ High"
        elif commits > 100:
            activity = "📊 Moderate"
        else:
            activity = "🌱 Growing"
        
        lines.append(f"| **{copy['dev_type']}** | **{copy['activity_level']}** | **GitScore** |")
        lines.append(f"|---|---|---|")
        lines.append(f"| {dev_type} | {activity} | {gitscore.total:.1f}/100 |")
        lines.append("")
        lines.append(f"### {copy['repo_stats']}")
        lines.append("")
        lines.append(f"- **{copy['total_repos']}:** {repo_count}")
        lines.append(f"- **{copy['total_stars']}:** {total_stars} ⭐")
        lines.append(f"- **{copy['total_forks']}:** {total_forks} 🔀")
        lines.append(f"- **{copy['avg_stars']}:** {avg_stars:.1f}")
        
        return "\n".join(lines)
    
    def _build_gitscore_visual(self, gitscore: GitScore, copy: dict) -> str:
        """Build visual GitScore representation with progress bars."""
        lines = []
        dimensions = [
            ("impact", copy['project_impact'], 35),
            ("contribution", copy['code_contribution'], 25),
            ("community", copy['community_activity'], 20),
            ("tech_breadth", copy['tech_breadth'], 15),
            ("documentation", copy['documentation'], 5),
        ]
        
        lines.append(f"### {copy['score_breakdown']}")
        lines.append("")
        
        for dim_key, label, max_val in dimensions:
            score = gitscore.dimensions.get(dim_key, 0.0)
            percentage = (score / max_val * 100) if max_val > 0 else 0
            bar_length = int(percentage / 5)  # 20 chars = 100%
            bar = "█" * bar_length + "░" * (20 - bar_length)
            lines.append(f"- **{label}:** `{bar}` {score:.1f}/{max_val}")
        
        return "\n".join(lines)
    
    def _build_achievements(self, user_data: UserData, gitscore: GitScore, copy: dict) -> str:
        """Build achievements section based on user data."""
        achievements = []
        dimensions = gitscore.dimensions
        
        # High impact achievement
        if dimensions.get("impact", 0) > 20:
            achievements.append(f"- 🌟 **{copy['high_impact']}** - Project impact score exceeds 20/35")
        
        # Active contributor
        if user_data.contributions.total_commits_last_year > 500:
            achievements.append(f"- 🔥 **{copy['active_contributor']}** - Over 500 commits in the last year")
        
        # Diverse skills
        if dimensions.get("tech_breadth", 0) > 10:
            achievements.append(f"- 🎯 **{copy['diverse_skills']}** - Strong technical breadth")
        
        # Well documented
        if dimensions.get("documentation", 0) > 3:
            achievements.append(f"- 📝 **{copy['well_documented']}** - Excellent documentation practices")
        
        # Popular repo
        max_stars = max((repo.stars for repo in user_data.repositories), default=0)
        if max_stars > 50:
            achievements.append(f"- ⭐ **{copy['popular_repo']}** - Repository with {max_stars}+ stars")
        
        # Consistent committer
        if user_data.contributions.longest_streak > 30:
            achievements.append(f"- 📅 **{copy['consistent']}** - {user_data.contributions.longest_streak} day contribution streak")
        
        if not achievements:
            achievements.append(f"- 🌱 **Growing Developer** - Building skills and contributions")
        
        return "\n".join(achievements)
    
    def _build_tech_stack(self, user_data: UserData, copy: dict) -> str:
        """Build tech stack section with visual language distribution."""
        lines = []
        
        if not user_data.languages:
            return f"{copy['language_unavailable']}"
        
        total_bytes = sum(user_data.languages.values())
        sorted_langs = sorted(user_data.languages.items(), key=lambda x: x[1], reverse=True)[:8]
        
        lines.append(f"### {copy['language_distribution']}")
        lines.append("")
        
        for lang, bytes_count in sorted_langs:
            percentage = (bytes_count / total_bytes * 100) if total_bytes > 0 else 0.0
            bar_length = int(percentage / 2)  # 50 chars = 100%
            bar = "█" * bar_length + "░" * (50 - bar_length)
            lines.append(f"- **{lang}:** `{bar}` {percentage:.1f}%")
        
        return "\n".join(lines)
    
    def _build_technical_skills(self, user_data: UserData, copy: dict) -> str:
        """Build technical skills section."""
        lines = []
        skills_service = SkillsInferenceService()
        skills_by_level = skills_service.infer_skills(user_data)
        specializations = skills_service.infer_specializations(user_data)
        
        if specializations:
            lines.append(f"**{copy['specializations']}:** {', '.join(specializations)}")
            lines.append("")
        
        for level in ["Expert", "Proficient", "Familiar", "Learning"]:
            skills = skills_by_level.get(level, [])
            if skills:
                level_label = copy.get(level.lower(), level)
                lines.append(f"- **{level_label}:** {', '.join(skills)}")
        
        return "\n".join(lines)
    
    def _build_notable_projects_enhanced(self, user_data: UserData, copy: dict) -> str:
        """Build enhanced notable projects section."""
        lines = []
        top_repos = sorted(
            user_data.repositories,
            key=lambda repo: (repo.stars, repo.forks),
            reverse=True,
        )[:5]

        if not top_repos:
            return f"{copy['no_projects']}"
        
        for index, repo in enumerate(top_repos, start=1):
            # Project header with emoji based on stars
            if repo.stars >= 100:
                emoji = "🌟"
            elif repo.stars >= 10:
                emoji = "⭐"
            else:
                emoji = "📦"
            
            lines.append(f"### {emoji} {repo.name}")
            lines.append("")
            
            # Description
            if repo.description:
                lines.append(f"{repo.description}")
                lines.append("")
            
            # Metrics in a table-like format
            metrics = []
            if repo.stars > 0:
                metrics.append(f"⭐ {repo.stars} {copy['stars']}")
            if repo.forks > 0:
                metrics.append(f"🔀 {repo.forks} {copy['forks']}")
            if repo.language:
                metrics.append(f"📝 {repo.language}")
            
            if metrics:
                lines.append(" | ".join(metrics))
                lines.append("")
            
            lines.append("")
        
        return "\n".join(lines)
    
    def _build_ai_insights(self, ai_insights: AIInsights, copy: dict) -> str:
        """Build AI insights section."""
        lines = []
        
        if ai_insights.style_tags:
            lines.append(f"**{copy['style_tags']}:**")
            lines.append("")
            for tag in ai_insights.style_tags:
                lines.append(f"- {tag}")
            lines.append("")
        
        if ai_insights.tech_summary:
            lines.append(f"> 💡 **{copy['summary']}:** {ai_insights.tech_summary}")
            lines.append("")
        
        if ai_insights.roast_comment:
            lines.append(f"> 🔥 **{copy['roast']}:** *{ai_insights.roast_comment}*")
            lines.append("")
        
        if not lines:
            return f"{copy['ai_unavailable']}"
        
        return "\n".join(lines)

    def _build_key_strengths(self, gitscore: GitScore, user_data: UserData, copy: dict) -> str:
        """Build key strengths section based on GitScore dimensions."""
        strengths = []
        dimensions = gitscore.dimensions
        
        # Identify top 3 dimensions
        sorted_dims = sorted(
            [
                ("impact", dimensions.get("impact", 0.0), 35),
                ("contribution", dimensions.get("contribution", 0.0), 25),
                ("community", dimensions.get("community", 0.0), 20),
                ("tech_breadth", dimensions.get("tech_breadth", 0.0), 15),
                ("documentation", dimensions.get("documentation", 0.0), 5),
            ],
            key=lambda x: x[1] / x[2],  # Sort by percentage of max
            reverse=True,
        )
        
        # Map dimension names to descriptions
        dim_descriptions = {
            "impact": copy.get("project_impact", "Project Impact"),
            "contribution": copy.get("code_contribution", "Code Contribution"),
            "community": copy.get("community_activity", "Community Activity"),
            "tech_breadth": copy.get("tech_breadth", "Tech Breadth"),
            "documentation": copy.get("documentation", "Documentation"),
        }
        
        for dim_key, score, max_score in sorted_dims[:3]:
            percentage = (score / max_score * 100) if max_score > 0 else 0.0
            if percentage >= 50:  # Only include if at least 50% of max
                strengths.append(f"- **{dim_descriptions[dim_key]}**: {score:.1f}/{max_score} ({percentage:.0f}%)")
        
        if not strengths:
            strengths.append(f"- {copy.get('generalist', 'Generalist')} developer with balanced skills")
        
        return "\n".join(strengths)

    def _build_notable_projects(self, top_repos: List, copy: dict) -> str:
        """Build notable projects section with enhanced formatting."""
        projects = []
        for index, repo in enumerate(top_repos, start=1):
            project_line = f"{index}. **{repo.name}**"
            
            # Add metrics inline
            metrics = []
            if repo.stars > 0:
                metrics.append(f"⭐ {repo.stars}")
            if repo.forks > 0:
                metrics.append(f"🔀 {repo.forks}")
            if metrics:
                project_line += f" — {' | '.join(metrics)}"
            
            projects.append(project_line)
            
            # Add description if available
            if repo.description:
                projects.append(f"   {repo.description}")
            
            # Add language if available
            if repo.language:
                projects.append(f"   **{copy['language']}:** {repo.language}")
        
        return "\n".join(projects)

    def _build_contribution_timeline(self, user_data: UserData, copy: dict) -> str:
        """Build contribution timeline/heatmap summary."""
        timeline = []
        timeline.append(f"- {copy['total_commits']}: {user_data.contributions.total_commits_last_year}")
        timeline.append(f"- {copy['total_pull_requests']}: {user_data.contributions.total_prs_last_year}")
        timeline.append(f"- {copy['followers']}: {user_data.followers}")
        timeline.append(f"- {copy['following']}: {user_data.following}")
        
        if user_data.contributions.longest_streak > 0:
            timeline.append(f"- {copy['longest_streak']}: {user_data.contributions.longest_streak} {copy['days']}")
        
        # Calculate average commits per day
        avg_commits = user_data.contributions.total_commits_last_year / 365
        timeline.append(f"- Average commits per day: {avg_commits:.2f}")
        
        return "\n".join(timeline)

    def build_card_data(
        self,
        user_data: UserData,
        gitscore: GitScore,
        ai_insights: AIInsights,
    ) -> CardData:
        """Build structured social card data for frontend rendering."""
        top_languages = [
            language
            for language, _ in sorted(
                user_data.languages.items(),
                key=lambda item: item[1],
                reverse=True,
            )[:5]
        ]

        return CardData(
            username=user_data.username,
            avatar_url=user_data.avatar_url,
            gitscore=gitscore.total,
            radar_chart_data=[
                gitscore.dimensions.get("impact", 0.0),
                gitscore.dimensions.get("contribution", 0.0),
                gitscore.dimensions.get("community", 0.0),
                gitscore.dimensions.get("tech_breadth", 0.0),
                gitscore.dimensions.get("documentation", 0.0),
            ],
            style_tags=ai_insights.style_tags[:5],
            roast_comment=ai_insights.roast_comment,
            tech_icons=top_languages,
        )

    def generate_social_card_html(
        self,
        card_data: CardData,
        tech_summary: str = "",
        theme: str = "dark",
        language: str = "en",
    ) -> str:
        """Generate a localized HTML snapshot for social card rendering."""
        copy = self.COPY[language]
        is_dark = theme == "dark"
        
        # Light mode colors
        if not is_dark:
            background = "#efe8dc"
            panel = "#fbf7f0"
            text = "#2a2621"
            muted = "#6d6458"
            accent = "#8b6b3f"
            tag_bg = "#b77932"
            gradient_start = "rgba(183, 121, 50, 0.28)"
            gradient_end = "rgba(152, 124, 76, 0.22)"
        # Dark mode colors
        else:
            background = "#17181c"
            panel = "#232428"
            text = "#f2ede3"
            muted = "#b8afa1"
            accent = "#d2ab67"
            tag_bg = "#e2bb78"
            gradient_start = "rgba(210, 171, 103, 0.28)"
            gradient_end = "rgba(186, 148, 94, 0.22)"
        tags = "".join(
            f"<span style='padding:8px 12px;border-radius:999px;background:{tag_bg};color:{'#09111f' if not is_dark else '#ffffff'};"
            f"font-size:18px;font-weight:700'>{tag}</span>"
            for tag in card_data.style_tags[:4]
        )
        tech_stack = " · ".join(card_data.tech_icons[:4]) or copy["generalist"]
        summary = tech_summary or copy["card_fallback"]
        
        # Shadow color based on theme
        shadow = "rgba(15, 23, 42, 0.25)" if not is_dark else "rgba(0, 0, 0, 0.4)"

        return f"""<!DOCTYPE html>
<html lang="{copy['lang']}">
  <body style="margin:0;font-family:Segoe UI,Arial,sans-serif;background:{background};">
    <div style="width:1200px;height:630px;padding:48px;box-sizing:border-box;background:
      radial-gradient(circle at top right, {gradient_start}, transparent 35%),
      radial-gradient(circle at bottom left, {gradient_end}, transparent 30%),
      {background}; color:{text};">
      <div style="height:100%;border-radius:32px;background:{panel};padding:40px;box-sizing:border-box;
        display:flex;flex-direction:column;justify-content:space-between;box-shadow:0 24px 80px {shadow};">
        <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:32px;">
          <div style="display:flex;gap:24px;align-items:center;">
            <img src="{card_data.avatar_url}" alt="{card_data.username}" style="width:112px;height:112px;border-radius:28px;border:4px solid {accent};object-fit:cover;" />
            <div>
              <div style="font-size:20px;color:{muted};letter-spacing:0.08em;text-transform:uppercase;">Codefolio</div>
              <div style="font-size:44px;font-weight:800;line-height:1.1;color:{text};">@{card_data.username}</div>
              <div style="margin-top:8px;font-size:22px;color:{muted};">{tech_stack}</div>
            </div>
          </div>
          <div style="text-align:right;">
            <div style="font-size:18px;color:{muted};">GitScore</div>
            <div style="font-size:76px;font-weight:900;color:{accent};line-height:1;">{card_data.gitscore:.1f}</div>
          </div>
        </div>
        <div>
          <div style="font-size:30px;font-weight:700;line-height:1.4;color:{text};">{summary}</div>
          <div style="margin-top:24px;display:flex;gap:12px;flex-wrap:wrap;">{tags}</div>
        </div>
        <div style="display:flex;justify-content:space-between;align-items:flex-end;gap:32px;">
          <div style="font-size:24px;color:{muted};max-width:760px;">{card_data.roast_comment or copy["card_roast_fallback"]}</div>
          <div style="display:grid;grid-template-columns:repeat(5, 1fr);gap:12px;min-width:340px;">
            {self._build_metric_cells(card_data.radar_chart_data, accent, muted, copy["card_metrics"], is_dark)}
          </div>
        </div>
      </div>
    </div>
  </body>
</html>"""

    def generate_pdf_resume(self, markdown_resume: str) -> bytes:
        """Generate a lightweight PDF without requiring extra dependencies."""
        content_lines = self._wrap_markdown_for_pdf(markdown_resume)
        stream_lines: List[str] = ["BT", "/F1 10 Tf", "50 792 Td", "14 TL"]
        first_line = True
        for line in content_lines:
            escaped = self._escape_pdf_text(line)
            if not first_line:
                stream_lines.append("T*")
            stream_lines.append(f"({escaped}) Tj")
            first_line = False
        stream_lines.append("ET")
        stream = "\n".join(stream_lines).encode("latin-1", errors="replace")

        objects = [
            b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
            b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
            b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
            b"4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
            f"5 0 obj << /Length {len(stream)} >> stream\n".encode("latin-1") + stream + b"\nendstream endobj",
        ]

        pdf = bytearray(b"%PDF-1.4\n")
        offsets = [0]
        for obj in objects:
            offsets.append(len(pdf))
            pdf.extend(obj)
            pdf.extend(b"\n")

        xref_offset = len(pdf)
        pdf.extend(f"xref\n0 {len(offsets)}\n".encode("latin-1"))
        pdf.extend(b"0000000000 65535 f \n")
        for offset in offsets[1:]:
            pdf.extend(f"{offset:010d} 00000 n \n".encode("latin-1"))
        pdf.extend(
            f"trailer << /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF".encode("latin-1")
        )

        return bytes(pdf)

    def _build_metric_cells(
        self,
        values: List[float],
        accent: str,
        muted: str,
        labels: List[str],
        is_dark: bool = True,
    ) -> str:
        cells = []
        bg_color = "rgba(255, 255, 255, 0.04)" if is_dark else "rgba(139, 107, 63, 0.10)"
        for label, value in zip(labels, values):
            cells.append(
                f"<div style='padding:12px 10px;border-radius:18px;background:{bg_color};text-align:center'>"
                f"<div style='font-size:14px;color:{muted}'>{label}</div>"
                f"<div style='margin-top:6px;font-size:26px;font-weight:800;color:{accent}'>{value:.1f}</div>"
                f"</div>"
            )
        return "".join(cells)

    def _wrap_markdown_for_pdf(self, markdown_resume: str) -> List[str]:
        lines: List[str] = []
        for raw_line in markdown_resume.splitlines():
            line = raw_line.strip()
            if not line:
                lines.append("")
                continue
            lines.extend(wrap(line, width=85) or [""])
        return lines

    def _escape_pdf_text(self, text: str) -> str:
        return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
